use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};
use x25519_dalek::{PublicKey, StaticSecret};

use crate::SecretError;
use crate::parse::KEY_LEN;

/// The length of an Ed25519 signature.
pub const SIGNATURE_LEN: usize = 64;

/// Fill a fresh key from the operating system's randomness.
///
/// The bytes are stored exactly as they come out and are not clamped. `wg genkey` clamps
/// before it writes, so a key generated here and a key generated by `wg` can differ in the
/// bits clamping touches; the X25519 public key derived from either is the same, because
/// the curve clamps when the key is used, not when it is stored.
pub fn random_key() -> Result<[u8; KEY_LEN], SecretError> {
    let mut bytes = [0u8; KEY_LEN];
    getrandom::fill(&mut bytes).map_err(|source| SecretError::Randomness { source })?;
    Ok(bytes)
}

/// The X25519 public key of a tunnel key, as `wg pubkey` computes it.
pub fn x25519_public_key(secret: &[u8; KEY_LEN]) -> [u8; KEY_LEN] {
    let secret = StaticSecret::from(*secret);
    PublicKey::from(&secret).to_bytes()
}

/// The Ed25519 public key of a signing key.
pub fn ed25519_public_key(secret: &[u8; KEY_LEN]) -> [u8; KEY_LEN] {
    SigningKey::from_bytes(secret).verifying_key().to_bytes()
}

/// Sign a message with an Ed25519 key.
pub fn sign(secret: &[u8; KEY_LEN], message: &[u8]) -> Result<[u8; SIGNATURE_LEN], SecretError> {
    let signing = SigningKey::from_bytes(secret);
    let signature = signing
        .try_sign(message)
        .map_err(|error| SecretError::Signing {
            reason: error.to_string(),
        })?;
    Ok(signature.to_bytes())
}

/// Whether a signature was made over this message by the holder of this public key.
pub fn verify(public: &[u8; KEY_LEN], message: &[u8], signature: &[u8; SIGNATURE_LEN]) -> bool {
    let Ok(verifying) = VerifyingKey::from_bytes(public) else {
        return false;
    };
    let signature = Signature::from_bytes(signature);
    verifying.verify_strict(message, &signature).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key() -> [u8; KEY_LEN] {
        match random_key() {
            Ok(key) => key,
            Err(error) => panic!("randomness: {error}"),
        }
    }

    #[test]
    fn two_generated_keys_are_not_the_same_key() {
        assert_ne!(key(), key());
    }

    #[test]
    fn a_public_key_depends_on_the_private_key_alone() {
        let secret = key();
        assert_eq!(x25519_public_key(&secret), x25519_public_key(&secret));
        assert_eq!(ed25519_public_key(&secret), ed25519_public_key(&secret));
        assert_ne!(x25519_public_key(&secret), ed25519_public_key(&secret));
        let other = key();
        assert_ne!(x25519_public_key(&secret), x25519_public_key(&other));
    }

    #[test]
    fn a_signature_verifies_and_a_changed_message_does_not() {
        let secret = key();
        let public = ed25519_public_key(&secret);
        let signature = match sign(&secret, b"GET /v1/config") {
            Ok(signature) => signature,
            Err(error) => panic!("signing: {error}"),
        };
        assert!(verify(&public, b"GET /v1/config", &signature));
        assert!(!verify(&public, b"GET /v1/rotate", &signature));

        let mut tampered = signature;
        tampered[0] ^= 0x01;
        assert!(!verify(&public, b"GET /v1/config", &tampered));
    }

    #[test]
    fn a_signature_does_not_verify_under_another_key() {
        let secret = key();
        let signature = match sign(&secret, b"join") {
            Ok(signature) => signature,
            Err(error) => panic!("signing: {error}"),
        };
        let other = key();
        assert!(!verify(&ed25519_public_key(&other), b"join", &signature));
    }

    #[test]
    fn a_public_key_that_is_not_a_point_verifies_nothing() {
        let signature = match sign(&key(), b"join") {
            Ok(signature) => signature,
            Err(error) => panic!("signing: {error}"),
        };
        assert!(!verify(&[0xff; KEY_LEN], b"join", &signature));
    }

    #[test]
    fn the_curves_agree_with_an_independent_implementation() {
        // The seed 000102...1f, run through RFC 7748 and RFC 8032 by the `cryptography`
        // Python package (OpenSSL's implementation). Ed25519 is deterministic, so the
        // signature over "wgmesh" is too, and both halves are worth pinning here.
        let mut secret = [0u8; KEY_LEN];
        for (index, byte) in secret.iter_mut().enumerate() {
            *byte = index as u8;
        }
        assert_eq!(
            hex(&x25519_public_key(&secret)),
            "8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f"
        );
        assert_eq!(
            hex(&ed25519_public_key(&secret)),
            "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
        );
        let signature = match sign(&secret, b"wgmesh") {
            Ok(signature) => signature,
            Err(error) => panic!("signing: {error}"),
        };
        assert_eq!(
            hex(&signature),
            "348a5047b1b03c6b18495f8ce0f4e6d1d376ac0a803759eb93fa08b3028d2d5f\
             63262985e90361a828836aef66887eb0d81568525a51dbc6923d9fcaca59170d"
        );
        assert!(verify(&ed25519_public_key(&secret), b"wgmesh", &signature));
    }

    fn hex(bytes: &[u8]) -> String {
        bytes.iter().map(|byte| format!("{byte:02x}")).collect()
    }

    #[test]
    fn the_clamping_that_the_curve_does_is_the_one_wireguard_does() {
        // A key whose first and last bytes have to be clamped before use.
        let mut secret = [0u8; KEY_LEN];
        secret[0] = 0xff;
        secret[31] = 0xff;
        let unclamped = x25519_public_key(&secret);
        let mut expected = secret;
        expected[0] &= 248;
        expected[31] &= 127;
        expected[31] |= 64;
        assert_eq!(
            unclamped,
            x25519_public_key(&expected),
            "clamping is not applied the way RFC 7748 describes"
        );
    }
}
